### ISSUE TITLE
could not be resolved from current working directory

### ISSUE THREAD

**Issue by afreisinger** [rsteube/jsonresume-headless#2]
Hi rsteube !
When I execute ./resume-cli.sh export resume.html -f html --theme flat

the cli show me, next output ->

/usr/local/lib/node_modules/resume-cli/build/render-html.js:46
    throw new Error(`theme path ${themePath} could not be resolved from current working directory`);
          ^
Error: theme path jsonresume-theme-flat could not be resolved from current working directory
    at _default (/usr/local/lib/node_modules/resume-cli/build/render-html.js:46:11)
    at createHtml (/usr/local/lib/node_modules/resume-cli/build/export-resume.js:84:46)
    at module.exports (/usr/local/lib/node_modules/resume-cli/build/export-resume.js:36:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/resume-cli/build/main.js:67:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async /usr/local/lib/node_modules/resume-cli/build/main.js:79:3

Any idea what's wrong ?
Adrian

**Comment by rsteube** [comment]
No, got the same error. `serve` works though :thinking: .
Might be related to the way it is installed (globaly/locally): https://github.com/jsonresume/resume-cli/issues/243

**Comment by rsteube** [comment]
@afreisinger not fixed yet, but i found [this little marvel](https://twitter.com/saurabhdutta73/status/1405312938169282563).
Put it in a container [here](https://github.com/rsteube/jsonresume-theme-aurora-docker) if you're interested.
